const senators = [
  'Richard Shelby (Alabama)',
  'Doug Jones (Alabama)',
  'Lisa Murkowski (Alaska)',
  'Dan Sullivan (Alaska)',
  'Kyrsten Sinema (Arizona)',
  'Martha McSally (Arizona)',
  'John Boozman (Arkansas)',
  'Tom Cotton (Arkansas)',
  'Dianne Feinstein (California)',
  'Kamala Harris (California)',
  'Michael Bennet (Colorado)',
  'Cory Gardner (Colorado)',
  'Richard Blumenthal (Connecticut)',
  'Chris Murphy (Connecticut)',
  'Tom Carper (Delaware)',
  'Chris Coons (Delaware)',
  'Marco Rubio (Florida)',
  'Rick Scott (Florida)',
  'David Perdue (Georgia)',
  'Kelly Loeffler (Georgia)',
  'Brian Schatz (Hawaii)',
  'Mazie Hirono (Hawaii)',
  'Mike Crapo (Idaho)',
  'Jim Risch (Idaho)',
  'Dick Durbin (Illinois)',
  'Tammy Duckworth (Illinois)',
  'Todd Young (Indiana)',
  'Mike Braun (Indiana)',
  'Chuck Grassley (Iowa)',
  'Joni Ernst (Iowa)',
  'Pat Roberts (Kansas)',
  'Jerry Moran (Kansas)',
  'Mitch McConnell (Kentucky)',
  'Rand Paul (Kentucky)',
  'Bill Cassidy (Louisiana)',
  'John Kennedy (Louisiana)',
  'Susan Collins (Maine)',
  'Angus King (Maine)',
  'Ben Cardin (Maryland)',
  'Chris Van Hollen (Maryland)',
  'Elizabeth Warren (Massachusetts)',
  'Ed Markey (Massachusetts)',
  'Debbie Stabenow (Michigan)',
  'Gary Peters (Michigan)',
  'Amy Klobuchar (Minnesota)',
  'Tina Smith (Minnesota)',
  'Roger Wicker (Mississippi)',
  'Cindy Hyde-Smith (Mississippi)',
  'Thad Cochran (Mississippi)',
  'Roy Blunt (Missouri)',
  'Josh Hawley (Missouri)',
  'John Tester (Montana)',
  'Steve Daines (Montana)',
  'Deb Fischer (Nebraska)',
  'Ben Sasse (Nebraska)',
  'Catherine Cortez Masto (Nevada)',
  'Jacky Rosen (Nevada)',
  'Jeanne Shaheen (New Hampshire)',
  'Maggie Hassan (New Hampshire)',
  'Bob Menendez (New Jersey)',
  'Cory Booker (New Jersey)',
  'Tom Udall (New Mexico)',
  'Martin Heinrich (New Mexico)',
  'Chuck Schumer (New York)',
  'Kirsten Gillibrand (New York)',
  'Richard Burr (North Carolina)',
  'Thom Tillis (North Carolina)',
  'John Hoeven (North Dakota)',
  'Kevin Cramer (North Dakota)',
  'Sherrod Brown (Ohio)',
  'Rob Portman (Ohio)',
  'Jim Inhofe (Oklahoma)',
  'James Lankford (Oklahoma)',
  'Ron Wyden (Oregon)',
  'Jeff Merkley (Oregon)',
  'Bob Casey Jr (Pennsylvania)',
  'Pat Toomey (Pennsylvania)',
  'Jack Reed (Rhode Island)',
  'Sheldon Whitehouse (Rhode Island)',
  'Lindsey Graham (South Carolina)',
  'Tim Scott (South Carolina)',
  'John Thune (South Dakota)',
  'Mike Rounds (South Dakota)',
  'Lamar Alexander (Tennessee)',
  'Marsha Blackburn (Tennessee)',
  'John Cornyn (Texas)',
  'Ted Cruz (Texas)',
  'Mike Lee (Utah)',
  'Mitt Romney (Utah)',
  'Patrick Leahy (Vermont)',
  'Bernie Sanders (Vermont)',
  'Mark Warner (Virginia)',
  'Tim Kaine (Virginia)',
  'Patty Murray (Washington)',
  'Maria Cantwell (Washington)',
  'Joe Manchin (West Virginia)',
  'Shelley Moore Capito (West Virginia)',
  'Ron Johnson (Wisconsin)',
  'Tammy Baldwin (Wisconsin)',
  'Mike Enzi (Wyoming)',
  'John Barrasso (Wyoming)',
]

export default senators