name: Update campaign finance data from Cal-Access
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: jruipinto/ImageMagick-action@v1
    - name: Install Node dependencies
      run: npm install
    - name: Run scripts
      run: |-
        npm start
